### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by Akhtar303** [farazBhatti/Weapon-Detection-in-CCTV-Footage#1]
Hi @farazBhatti 
can you share your pretrained model
Thanks

**Comment by farazBhatti** [comment]
Hi @Akhtar303 , thank you for showing interest. Ive mentioned download link in [Readme](https://github.com/farazBhatti/Weapon-Detection-in-CCTV-Footage#pre-trained-model-weights).

**Comment by Akhtar303** [comment]
> Hi @Akhtar303 , thank you for showing interest. Ive mentioned download link in [Readme](https://github.com/farazBhatti/Weapon-Detection-in-CCTV-Footage#pre-trained-model-weights).

@farazBhatti  Thnks for your reply 
This is your weapon model which you trained i.e "yolov3.weights"
I have  used your webcam_VGG.py chage this line model = load_model(config.MODEL_PATH)
to  model = load_model("weights/yolov3.weights") i.e give path of your model which you give link in Readme file but it doesn't work
Thanks

**Comment by farazBhatti** [comment]
Thanks for pointing it out. Ive updated ReadMe page.Please note  this repository may have untested code as i am in the process of submitting a paper. After paper submission I will update it and give fully optimized/trained model for both VGG(for image classification ) and YOLO(for object detection)
